name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        cabal: ["3.0"]
        ghc: ["8.8", "8.10"]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Haskell
        uses: actions/setup-haskell@v1.1.3
        with:
          cabal-version: ${{ matrix.cabal }}
          ghc-version: ${{ matrix.ghc }}

      - name: Build
        run: cabal build --enable-tests --enable-benchmarks all

      - name: Run tests
        run: cabal test all
